---
version: "3.8"
services:
  prd-dsmr-reader-app:
    image: docker-registry.theautomation.nl/coen/prd-dsmr-reader-app:latest
    container_name: prd-dsmr-reader-app
    depends_on:
      - prd-dsmr-reader-db
    cap_add:
      - NET_ADMIN
    restart: always
    env_file: prd-dsmr-reader-app.env
    ports:
      - 7777:80
    networks:
      - dsmr-reader
      - mosquitto
    volumes:
      - ./dsmr_backups:/dsmr/backups

  prd-dsmr-reader-db:
    image: docker-registry.theautomation.nl/coen/prd-dsmr-reader-db:latest
    container_name: prd-dsmr-reader-db
    restart: always
    env_file: prd-dsmr-reader-db.env
    networks:
      - dsmr-reader
    volumes:
      - ./dsmrdb:/var/lib/postgresql/data

networks:
  mosquitto:
    name: mosquitto
  dsmr-reader:
    name: dsmr-reader
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
